name: sync
on:
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    name: sync
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: 'Github'
          author_email: 'open-source@deuxhuithuit.com'
      - uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.SYNC_TOKEN }}
          src_path: dist/.
          src_branch: master
          dst_path: src/core/.
          dst_owner: deuxhuithuit
          dst_branch: main
          dst_repo_name: javascript
          clean: true
          commit_message: (Automated) framework sync
